# Generated by Django 5.2.15 on 2026-06-14 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('type', models.CharField(choices=[('choice', 'Single choice'), ('multichoice', 'Multiple choice'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.category')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='filters.categoryfilter')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductFilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='filters.categoryfilter')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='filters.categoryfilteroption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_values', to='catalog.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categoryfilter',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_filter_slug_per_category'),
        ),
        migrations.AddIndex(
            model_name='productfiltervalue',
            index=models.Index(fields=['product', 'filter'], name='filters_pro_product_43940d_idx'),
        ),
        migrations.AddIndex(
            model_name='productfiltervalue',
            index=models.Index(fields=['filter', 'option'], name='filters_pro_filter__3bc987_idx'),
        ),
        migrations.AddIndex(
            model_name='productfiltervalue',
            index=models.Index(fields=['filter', 'value_number'], name='filters_pro_filter__3fce6e_idx'),
        ),
    ]
